# Generated by Django 3.2.9 on 2022-01-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=200),
        ),
    ]
